name: branchwater-dev
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sourmash-minimal>=4.8.14,<5
    - pip
    - rust=1.75
    - maturin>=1,<2
    - pytest
    - pandas
    - compilers
    - clang
